feat: SJRA-828 & SJRA-829 Update sequencing experiment, task, document to model v2  (#806)
* feat: SJRA-828 sql scripts to update model and test datas

* feat: SJRA-828 wip update model to v2

* feat: SJRA-828 wip update to model v2

* feat" SJRA-828 fix documents tests

* feat: SJRA-828 fix variants and occurrences

* feat: SJRA-828 add case id in interpretations and some fixs in the front-end to support new model

* feat: SJRA-828 update IGV backend

* feat: SJRA-828 fix documents tests after igv update

* feat: SJRA-829 update task types

* feat: SJRA-828 update in front-end after changes in model

* feat: SJRA-829 remove comment

* feat: SJRA-828 remove document_has_patient

* feat: SJRA-829 update igv frontend components

* feat: SJRA-828 edit fe components for igv

* feat: sjra-849 fixed date of birth validation and tests (#804)

* feat: SJRA-847 Added data manager role check for get batches (#805)

* feat: sjra-847 added data manager role check for get batches and made mock auth configurable

* feat: sjra-847 cleaned user preferences test

* feat: SJRA-851 Add SNV facets Cypress tests

* feat: SJRA-828 update igv query

* feat: SJRA-828 fix igv integration test

---------

Co-authored-by: Karl Ritchie <ritchie.karl@gmail.com>
Co-authored-by: Charles Morin <charles.mor@outlook.fr>
Co-authored-by: kstonge <karine.st-onge.hsj@ssss.gouv.qc.ca>

diff --git a/backend/docker-compose.yml b/backend/docker-compose.yml
--- a/backend/docker-compose.yml
+++ b/backend/docker-compose.yml
@@ -50,19 +50,19 @@ services:
     ports:
       - "8080:8080"
       - "9000:9000"
-  openfga:
-    image: openfga/openfga:latest
-    container_name: openfga
-    ports:
-      - "3000:3000"
-      - "8081:8080"
-      - "8082:8081"
-    command: ["run", "--playground-enabled", "--playground-port=3000"]
-    healthcheck:
-      test: ["CMD-SHELL", "curl -f http://localhost:8081/health/live || exit 1"]
-      interval: 10s
-      timeout: 5s
-      retries: 5
+#  openfga:
+#    image: openfga/openfga:latest
+#    container_name: openfga
+#    ports:
+#      - "3000:3000"
+#      - "8081:8080"
+#      - "8082:8081"
+#    command: ["run", "--playground-enabled", "--playground-port=3000"]
+#    healthcheck:
+#      test: ["CMD-SHELL", "curl -f http://localhost:8081/health/live || exit 1"]
+#      interval: 10s
+#      timeout: 5s
+#      retries: 5
 
   api:
     build:
@@ -120,4 +120,4 @@ services:
     command:
       - -c
       - |
-        export PGPASSWORD='radiant'; psql -h postgres -U radiant -d radiant -f /docker-entrypoint-initdb.d/insert_clinical_data.sql;
+        export PGPASSWORD='radiant'; sleep 10 && psql -h postgres -U radiant -d radiant -f /docker-entrypoint-initdb.d/insert_clinical_data.sql;
